### PR TITLE
Support for additional query parameters for BTCBitcoinURL

### PR DESCRIPTION
**Pull request by aogden**
As discussed here:

<blockquote class="twitter-tweet" lang="en"><p><a href="https://twitter.com/Ogdagon">@Ogdagon</a> if you port those into BTCBitcoinURL, that&#39;d be awesome :-) Maybe `queryParameters` dict for all query string items.</p>&mdash; Oleg Andreev (@oleganza) <a href="https://twitter.com/oleganza/status/580754238747332609">March 25, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

### CODE REVIEW

**Comment by oleganza** [comment]
I think it's more practical and consistent to put *all* query string parameters in `queryParameters`. Including `"label"`, `"r"`, `"amount"` etc. When we add another convenience property to access one of them, we don't want to break code that reads that property from `queryParameters`.

**Comment by jsuder** [comment]
+1 to what @oleganza wrote.

**Comment by aogden** [comment]
Makes sense

**Comment by oleganza** [comment]
You don't need to close this. You may simply adjust the code, rebase and then we'll merge that.

**Comment by aogden** [comment]
How does this iteration look to you all?

**Comment by oleganza** [comment]
Thanks for update, great job! See my comments on your code lines. After a few fixes it'd be a great merge.

**Comment by aogden** [comment]
Thanks for the feedback, I'm learning a lot! I used the macros to avoid too much boilerplate code for standard query param getters/setters but I understand the issues with readability and complexity. I'll get those fixes in and update the pull request.

**Comment by aogden** [comment]
I addressed your notes for the last commit. Let me know how things are looking now!

**Comment by oleganza** [comment]
Very good, thanks. A couple of improvements and it'll be perfect.

**Comment by oleganza** [comment]
Funny, I have just contributed to another project and had to go through a ton of stylistic remarks myself. See https://github.com/btcsuite/btcd/pull/360

Totally worth it, though.

**Comment by aogden** [comment]
Agreed, totally worth it. Thanks for taking the time to remark! Just posted a new diff with lazy ivar assignments in getters and removing dictionary copy in getter

**Comment by aogden** [comment]
I squashed my commits and rebased onto latest master for your convenience

**Comment by oleganza** [comment]
Thanks, merged.

**Pull request merged**
