### PR TITLE
Add ArcBit to the list of projects that uses CoreBitcoin

### PR DESCRIPTION
**Pull request by stequald**
Hi Oleg, I would like to add ArcBit as a project that uses your CoreBitcoin library.

### CODE REVIEW

**Comment by oleganza** [comment]
I'd rather add a link to the Arcbit's homepage. http://arcbit.io

**Comment by stequald** [comment]
That works also. I've just updated this pull request to link to Arcbit's homepage.

**Comment by oleganza** [comment]
Thanks!

**Comment by stequald** [comment]
Awesome! And this is probably not the best place to say this, but I would like to say your doing amazing work with CoreBitcoin, ArcBit wouldn't be possible without it!

**Comment by oleganza** [comment]
@stequald Glad to hear that, thanks!

**Pull request merged**
