### PR TITLE
Added BTCKeychainTests.swift

### PR DESCRIPTION
**Pull request by rsmoz**

### CODE REVIEW

**Comment by rsmoz** [comment]
@oleganza hi, just checking in about the PR's status.

**Comment by oleganza** [comment]
Did you have Swift compiler crashes with "Segmentation fault: 11" when building swift tests?

**Comment by oleganza** [comment]
@rsmoz please see the comments "Crashes Xcode 7.1.1" https://github.com/oleganza/CoreBitcoin/commit/6691ce22c64249ffd61179545d70cf9038ef3785#diff-d0b138a739f62d4d01f790dbee73c6e1

Can you reproduce the "segmentation fault: 11" when you uncomment and try to build and run the tests?

**Comment by rsmoz** [comment]
Yep, it crashes.

**Pull request merged**
