### PR TITLE
Enable camera selection (back or front) on BTCQRCode

### PR DESCRIPTION
**Pull request by jagbolanos**
I came across the need to select the camera for the QR Code scanner so did a slight modification of **BTCQRCode**.

I hope you find it useful and if I need to follow some code convention just let me know.

### CODE REVIEW

**Comment by jagbolanos** [comment]
I also added the possibility to select the camera orientation. 

Explaining the scenario I cam across the camera selection and orientation problem when using the library over an iPad that is on top of a desk, so orientation is landscape and it uses the front camera

**Comment by oleganza** [comment]
Thanks. A suggestion for a neater API name: `scannerViewUsingDevice:orientation:block:`

**Comment by jagbolanos** [comment]
Cool, just changed it

**Comment by oleganza** [comment]
Thanks!

**Comment by jagbolanos** [comment]
Sure! Thanks to you, great library. I'll try to contribute more.

**Pull request merged**
