### PR TITLE
Completed remaining Swift tests

### PR DESCRIPTION
**Pull request by rsmoz**

### CODE REVIEW

**Comment by oleganza** [comment]
I'll try to check these over the weekend. Feel free to ping me if i don't.

**Comment by rsmoz** [comment]
:+1:

**Comment by rsmoz** [comment]
pong

**Comment by rsmoz** [comment]
@oleganza ping

Also, I'm curious (somewhat unrelated), have you ever thought about writing a full node implementation in Swift?

**Comment by oleganza** [comment]
ACK. Neat Swift implementation with API close to [BTCRuby](https://github.com/oleganza/btcruby) would be great.

**Pull request merged**
